version: "3.8"


services:
  postgres:
    image: postgres:latest
    container_name: vagafacil-mobile-back
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "vagafacil_mobile" 
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "12345678"